name: Build openSUSE

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  CI:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        llvm: [13, 14, 15, 16, 17]
        build-type: [DEBUG]
        include:
          - llvm: 17
            build-type: ASAN
          - llvm: 17
            build-type: UBSAN
          - llmv: 17
            build-type: RelWithDebInfo
            extra-flags: -flto=auto
          - llmv: 17
            build-type: RelWithDebInfo
            env: CC=clang CXX=clang++
      fail-fast: false

    container:
      image: opensuse/tumbleweed

    steps:
    - run: zypper -n install
        binutils clang${{ matrix.llvm }}-devel cmake flex gcc-c++ llvm${{ matrix.llvm }}-devel
        python3-Pebble python3-pytest unifdef python3-psutil curl git python3-chardet findutils
        python3-flake8
        python3-flake8-builtins
        python3-flake8-bugbear
        python3-flake8-import-order
        python3-flake8-quotes
        python3-pip
        sudo wget
    - run: zypper -n install python3-flake8-comprehensions sqlite-devel python3
    - run: pip install --break-system-packages pytest-cov
    - uses: rui314/setup-mold@v1
    - run: ld --version
    - uses: actions/checkout@v4
    - run: nproc
    - name: build
      run: |
            mkdir objdir
            cd objdir
            ${{ matrix.env }} cmake .. -DCMAKE_BUILD_TYPE=${{ matrix.build-type }} -DCMAKE_CXX_FLAGS=${{ matrix.extra-flags }}
            make -j`nproc` VERBOSE=1
    - name: flake8
      run: flake8
    - run: pip install --break-system-packages pyupgrade
    - run: find . -name '*.py' | xargs pyupgrade --py36-plus
    - name: test
      run: pytest
      working-directory: objdir
